# Generated by Django 4.1.7 on 2023-03-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('experiecer', models.CharField(blank=True, max_length=70, null=True)),
                ('profession', models.CharField(blank=True, max_length=70, null=True)),
                ('locality', models.CharField(blank=True, max_length=70, null=True)),
                ('ratings', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
