# Generated by Django 4.1.7 on 2023-03-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemaster',
            name='man_img',
            field=models.ImageField(default=11, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
