# Generated by Django 4.1.7 on 2023-03-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicemaster_man_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homemaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
                ('password', models.CharField(blank=True, max_length=70, null=True)),
                ('cnf_password', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
