# Generated by Django 3.2.18 on 2023-03-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_homemaster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homemaster',
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
