# Generated by Django 3.2.18 on 2023-03-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20230327_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceaddmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=70, null=True)),
                ('lname', models.CharField(blank=True, max_length=70, null=True)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(blank=True, max_length=70, null=True)),
                ('service', models.CharField(blank=True, max_length=70, null=True)),
                ('servicename', models.CharField(blank=True, max_length=70, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('pincode', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicemaster',
            name='created_by',
        ),
    ]
