# Generated by Django 4.1.7 on 2023-03-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_auto_20230328_1039"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceaddmaster",
            name="created_by",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
