# Generated by Django 4.1.7 on 2023-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_serviceaddmaster_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaddmaster',
            name='amount',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
